server:
  port: 9009

spring:
  rabbitmq:
    host: localhost

aliyun:
  sms:
    accessKeyId: accessKeyId
    accessKeySecret: accessKeySecret
    template_code: template_code
    sign_name: sign_name

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true