server:
  port: 9100

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    username: root
    password: root
mybatis:
  mapper-locations: mybatis/*.xml
logging:
  level:
    com.tensquare.mybatistest.mapper.*: debug