server:
  port: 9008

spring:
  application:
    name: tensquare-user

  redis:
    host: localhost

  rabbitmq:
    host: localhost

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_user?characterEncoding=utf-8
    username: root
    password: root

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

jwt:
  config:
    key: liuzhangtest
    ttl: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true


#zuul:
#  routes:
#    tensquare-base:
#      path: /base/**
#      serviceId: tensquare-base

#熔断器
feign:
  hystrix:
    enabled: true